social_pro_main_homepage:
    path:     /
    defaults: { _controller: SocialProMainBundle:SocialPro:index }
mainpage:
    path:     /mainpage
    defaults: { _controller: SocialProMainBundle:SocialPro:mainpage }

profile2:
    path:     /profile2
    defaults: { _controller: SocialProMainBundle:SocialPro:profile2 }

parametresprofil:
    path:     /paraprofile
    defaults: { _controller: SocialProMainBundle:SocialPro:parametresprofil }