social_pro_main_homepage:
    path:     /
    defaults: { _controller: SocialProMainBundle:SocialPro:index }
mainpage:
    path:     /mainpage
    defaults: { _controller: SocialProMainBundle:SocialPro:mainpage }

